<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

?>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              method="post"
              action="<?= $this->getUrl("testimonial/testimonial/save") ?>>"
              id="question-form"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset login" data-hasrequired="<?= $this->escapeHtml(__('* Required Fields')) ?>">
                <div class="field title required">
                    <label class="label" for="name"><span><?= $this->escapeHtml(__('Name')) ?></span></label>
                    <div class="control">
                        <input name="name" value="" type="text"
                               id="name" class="input-text"
                               title="<?= $this->escapeHtmlAttr(__('Name')) ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="email"><span><?= $this->escapeHtml(__('Email')) ?></span></label>
                    <div class="email">
                        <input name="email" value=""
                               id="email" type="text" class="input-text"
                               title="<?= $this->escapeHtmlAttr(__('Email')) ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="message"><span><?= $this->escapeHtml(__('Message')) ?></span></label>
                    <div class="message">
                        <input name="message" value=""
                               id="message" type="text" class="input-text"
                               title="<?= $this->escapeHtmlAttr(__('Message')) ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="company"><span><?= $this->escapeHtml(__('Company')) ?></span></label>
                    <div class="company">
                        <input name="company" value=""
                               id="company" type="text" class="input-text"
                               title="<?= $this->escapeHtmlAttr(__('Company')) ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="rating"><span><?= $this->escapeHtml(__('Rating')) ?></span></label>
                    <div class="rating">
                        <input name="rating" value=""
                               id="rating" type="number" class="input-text"
                               title="<?= $this->escapeHtmlAttr(__('Rating')) ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="status"><span><?= $this->escapeHtml(__('Status')) ?></span></label>
                    <select name="status" id="status">
                        <option value="0">Disable</option>
                        <option value="1">Enable</option>
                    </select>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action login primary" name="send" id="submit">
                            <span><?= $this->escapeHtml(__('Save')) ?></span>
                        </button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<!--<script type="text/javascript">-->
<!--    require(['jquery', 'mage/storage', 'mage/url'], function ($, storage, urlBuilder) {-->
<!--        $('#submit').on('click', function () {-->
<!--            var formData = new FormData($("#question-form")[0]);-->
<!--            formData = JSON.stringify(Object.fromEntries(formData));-->
<!--            storage.post(-->
<!--                urlBuilder.build("rest/V1/testimonial/save"),-->
<!--                JSON.stringify({data: formData})-->
<!--            ).done(function (r) {-->
<!--                window.location.replace(r);-->
<!--            }).fail(function (r) {-->
<!--                alert("Error");-->
<!--            });-->
<!--        });-->
<!--    });-->
<!--</script>-->
