<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/**
 * @var Index $block
 */

use Tigren\CustomerGroupCatalog\Block\CustomerGroup\Index;
$productCollection = $block->getProductCollection();

?>
<div class="table-wrapper orders-history">
    <h1>Rule Record</h1>
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php echo __('Rule Record') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('Order ID') ?></th>
            <th scope="col" class="col product"><?php echo __('Product ID') ?></th>
            <th scope="col" class="col product"><?php echo __('Customer ID') ?></th>
            <th scope="col" class="col customer"><?php echo __('Rule ID') ?></th>
            <th scope="col" class="col rule"><?php echo __('Created At ') ?></th>
            <th scope="col" class="col ">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($productCollection as $rule): ?>
            <tr>
                <td class="col shipping"><?php echo $rule->getOrderId() ?></td>
                <td class="col shipping"><?php echo $rule->getProductId() ?></td>
                <td class="col shipping"><?php echo $rule->getCustomerId() ?></td>
                <td class="col shipping"><?php echo $rule->getRuleId() ?></td>
                <td class="col date"><?php echo $rule->getCreatedAt() ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<button id="modal-btn">Test JS</button>
<div id="modal-content">
    <div class="modal-inner-content">
        <h2>Tigren</h2>
        <p>Hello</p>
    </div>
</div>
<script type="text/javascript">
    require(["jquery", "Magento_Ui/js/modal/modal"], function ($, modal) {
        var options = {
            type: 'popup',
            responsive: true,
            title: 'Bạn đang muốn test JS đúng không ?',
            buttons: [{
                text: 'Accept',
                class: 'modal-accept',
                click: function () {
                    alert('Success');
                    this.closeModal();
                }
            }, {
                text: 'Cancel',
                class: 'modal-close',
                click: function () {
                    this.closeModal();
                }
            }],
        };
        var popup = modal(options, $('#modal-content'));
        $("#modal-btn").click(function () {
            $('#modal-content').modal('openModal');
        });
    });
</script>
