<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

$priceModel = $this->getPriceType('regular_price');
$finalPriceModel = $this->getPriceType('final_price');
$idSuffix = $this->getIdSuffix() ? $this->getIdSuffix() : '';
$schema = ($this->getZone() == 'item_view') ? true : false;
?>
<?php if ($this->hasSpecialPrice()): ?>
    <span class="special-price">
        <?php echo $this->renderAmount($finalPriceModel->getAmount(), [
            'display_label' => __('Special Price'),
            'price_id' => $this->getPriceId('product-price-' . $idSuffix),
            'price_type' => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
    <span>
	<?php
    $item = $this->getSaleableItem();
    $_savePercent = 100 - round(((float)$item->getFinalPrice() / (float)$item->getPrice()) * 100);
    echo '<b style="color:#008000">' . $_savePercent . '% </b>';
    ?>
    </span>
    <span class="old-price">
        <?php echo $this->renderAmount($priceModel->getAmount(), [
            'display_label' => __('Regular Price'),
            'price_id' => $this->getPriceId('old-price-' . $idSuffix),
            'price_type' => 'oldPrice',
            'include_container' => true,
            'skip_adjustments' => true
        ]); ?>
    </span>
<?php else: ?>
    <?php echo $this->renderAmount($finalPriceModel->getAmount(), [
        'price_id' => $this->getPriceId('product-price-' . $idSuffix),
        'price_type' => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>

<?php if ($this->showMinimalPrice()): ?>
    <?php if ($this->getUseLinkForAsLowAs()): ?>
        <a href="<?= $this->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= $this->renderAmountMinimal() ?>
        </a>
    <?php else: ?>
        <span class="minimal-price-link">
            <?= $this->renderAmountMinimal() ?>
        </span>
    <?php endif ?>
<?php endif; ?>
